# Make a copy for your paper's Makefile.

# These variables are self-explanation. Mostly, you do not need to edit them.

## Paper's entry point. 
# MAIN     = 

## All figures includes in the paper.
# FIGURES  = 

## Bibfile except our all-in-one bib.
# BIBFILES = 

## Any dependencies else.
# OTHER    = 

include zebra-latex-goodies/Makefile
